export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Home } from "./Home";
export { default as Addmovie } from "./Addmovie";
export { default as Listmovie } from "./Listmovie";
export { default as Listuser } from "./Listuser";
export { default as Bookticket } from "./Bookticket";
export { default as Bookinghistory } from "./Bookinghistory";
export { default as Eticket } from "./Eticket";
export {default as Payment} from "./Payment";
